name: Build
on: push

jobs:
  build:
    name: Build SimpleFilter
    runs-on: windows-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4.2.2
        with:
          submodules: recursive

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0